- name: openrouter/google/gemini-2.0-flash-001
  edit_format: diff
  use_repo_map: true

- name: openrouter/openai/o3-mini
  edit_format: diff
  use_repo_map: true
  use_temperature: false
  editor_edit_format: editor-diff
  system_prompt_prefix: 'Formatting re-enabled. '

- name: openrouter/deepseek/deepseek-r1-distill-llama-70b
  edit_format: diff
  use_repo_map: true
  examples_as_sys_msg: true
  extra_params:
    max_tokens: 8192
  caches_by_default: true
  use_temperature: false
  editor_model_name: openrouter/deepseek/deepseek-chat
  editor_edit_format: editor-diff
